/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

/**
 *
 * @author HP
 */
public class JFMenuAdministrativos extends javax.swing.JFrame {

    /**
     * Creates new form JFMenuAdministrativos
     */
    public JFMenuAdministrativos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JbtnBuro = new javax.swing.JButton();
        JbtnBuro1 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        JbtnBuro2 = new javax.swing.JButton();
        JbtnBuro3 = new javax.swing.JButton();
        JbtnBuro4 = new javax.swing.JButton();
        JbtnBuro5 = new javax.swing.JButton();
        JbtnBuro6 = new javax.swing.JButton();
        JbtnBuro7 = new javax.swing.JButton();
        JbtnBuro8 = new javax.swing.JButton();
        JbtnBuro9 = new javax.swing.JButton();
        JbtnBuro10 = new javax.swing.JButton();
        JbtnBuro11 = new javax.swing.JButton();
        JbtnBuro12 = new javax.swing.JButton();
        JbtnBuro13 = new javax.swing.JButton();
        JbtnBuro14 = new javax.swing.JButton();
        JbtnBuro15 = new javax.swing.JButton();
        JbtnBuro16 = new javax.swing.JButton();
        JbtnBuro17 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        JbtnBuro.setBackground(new java.awt.Color(160, 16, 70));
        JbtnBuro.setForeground(new java.awt.Color(255, 255, 255));
        JbtnBuro.setText("REGISTRAR DOCENTE");
        JbtnBuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuroActionPerformed(evt);
            }
        });

        JbtnBuro1.setBackground(new java.awt.Color(160, 16, 70));
        JbtnBuro1.setForeground(new java.awt.Color(255, 255, 255));
        JbtnBuro1.setText("REGISTRAR ALUMNO");
        JbtnBuro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuro1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MENU JEFES DE DIVISIÓN");

        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(0, 102, 204));

        jButton1.setText("CERRAR SESION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        JbtnBuro2.setBackground(new java.awt.Color(160, 16, 70));
        JbtnBuro2.setForeground(new java.awt.Color(255, 255, 255));
        JbtnBuro2.setText("REGISTRAR JEFES DE DIVICIÓN");
        JbtnBuro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuro2ActionPerformed(evt);
            }
        });

        JbtnBuro3.setBackground(new java.awt.Color(160, 16, 70));
        JbtnBuro3.setForeground(new java.awt.Color(255, 255, 255));
        JbtnBuro3.setText("REGISTRAR CARRERA");
        JbtnBuro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuro3ActionPerformed(evt);
            }
        });

        JbtnBuro4.setBackground(new java.awt.Color(160, 16, 70));
        JbtnBuro4.setForeground(new java.awt.Color(255, 255, 255));
        JbtnBuro4.setText("REGISTRAR ASIGNATURA");
        JbtnBuro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuro4ActionPerformed(evt);
            }
        });

        JbtnBuro5.setBackground(new java.awt.Color(160, 16, 70));
        JbtnBuro5.setForeground(new java.awt.Color(255, 255, 255));
        JbtnBuro5.setText("REGISTRAR TEMA");
        JbtnBuro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuro5ActionPerformed(evt);
            }
        });

        JbtnBuro6.setBackground(new java.awt.Color(160, 16, 70));
        JbtnBuro6.setForeground(new java.awt.Color(255, 255, 255));
        JbtnBuro6.setText("REGISTRAR SUBTEMA");
        JbtnBuro6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuro6ActionPerformed(evt);
            }
        });

        JbtnBuro7.setBackground(new java.awt.Color(160, 16, 70));
        JbtnBuro7.setForeground(new java.awt.Color(255, 255, 255));
        JbtnBuro7.setText("REGISTRAR CICLO ESCOLAR");
        JbtnBuro7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuro7ActionPerformed(evt);
            }
        });

        JbtnBuro8.setBackground(new java.awt.Color(160, 16, 70));
        JbtnBuro8.setForeground(new java.awt.Color(255, 255, 255));
        JbtnBuro8.setText("REGISTRAR GRUPO");
        JbtnBuro8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuro8ActionPerformed(evt);
            }
        });

        JbtnBuro9.setBackground(new java.awt.Color(160, 16, 70));
        JbtnBuro9.setForeground(new java.awt.Color(255, 255, 255));
        JbtnBuro9.setText("REGISTRAR VERSIÓN");
        JbtnBuro9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuro9ActionPerformed(evt);
            }
        });

        JbtnBuro10.setBackground(new java.awt.Color(160, 16, 70));
        JbtnBuro10.setForeground(new java.awt.Color(255, 255, 255));
        JbtnBuro10.setText("ASIGNATURA_CURRICULAR");
        JbtnBuro10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuro10ActionPerformed(evt);
            }
        });

        JbtnBuro11.setBackground(new java.awt.Color(160, 16, 70));
        JbtnBuro11.setForeground(new java.awt.Color(255, 255, 255));
        JbtnBuro11.setText("ASIGNATURA_COCURRICULAR");
        JbtnBuro11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuro11ActionPerformed(evt);
            }
        });

        JbtnBuro12.setBackground(new java.awt.Color(160, 16, 70));
        JbtnBuro12.setForeground(new java.awt.Color(255, 255, 255));
        JbtnBuro12.setText("CARRERA_ASIGNATURA");
        JbtnBuro12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuro12ActionPerformed(evt);
            }
        });

        JbtnBuro13.setBackground(new java.awt.Color(160, 16, 70));
        JbtnBuro13.setForeground(new java.awt.Color(255, 255, 255));
        JbtnBuro13.setText("ASIGNATURA_TEMA");
        JbtnBuro13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuro13ActionPerformed(evt);
            }
        });

        JbtnBuro14.setBackground(new java.awt.Color(160, 16, 70));
        JbtnBuro14.setForeground(new java.awt.Color(255, 255, 255));
        JbtnBuro14.setText("TEMA_SUBTEMA");
        JbtnBuro14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuro14ActionPerformed(evt);
            }
        });

        JbtnBuro15.setBackground(new java.awt.Color(160, 16, 70));
        JbtnBuro15.setForeground(new java.awt.Color(255, 255, 255));
        JbtnBuro15.setText("DOCENTE_GRUPO");
        JbtnBuro15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuro15ActionPerformed(evt);
            }
        });

        JbtnBuro16.setBackground(new java.awt.Color(160, 16, 70));
        JbtnBuro16.setForeground(new java.awt.Color(255, 255, 255));
        JbtnBuro16.setText("ALUMNO_GRUPO");
        JbtnBuro16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuro16ActionPerformed(evt);
            }
        });

        JbtnBuro17.setBackground(new java.awt.Color(160, 16, 70));
        JbtnBuro17.setForeground(new java.awt.Color(255, 255, 255));
        JbtnBuro17.setText("GRUPO_VERSION");
        JbtnBuro17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuro17ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Materias con mayor indice de reprobados", "Calificaciones por  grupo", " " }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AUDITORIA ALUMNO", "AUDITORIA DOCENTE", "AUDITORIA JAFES DE DIVISION", "AUDITORIA GRUPO", "AUDITORIA CARRERA", "AUDITORIA ASIGNATURA", "AUDITORIA TEMA", "AUDITORIA TEMA_SUBTEMA", "AUDITORIA CICLO", "AUDITORIA DIRECCION", "AUDITORIA PERSONA", "AUDITORIA ASIGNATURA_CURRICULAR", "AUDITORIA ASIGNATURA_COCURRICULAR", "AUDITORIA TELEFONO", "AUDITORIA CORREO", "AUDITORIA CARRERA_ASIGNATURA", "AUDITORIA ASIGNATURA_TEMA", "AUDITORIA ALUMNO_GRUPO", "AUDITORIA DOCENTE_GRUPO", "AUDITORIA ALUMNO_VERSION", "AUDITORIA VERSION", " " }));

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setText("VER CONSULTA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setText("VER AUDITORIA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("SELECCIONE UNA OPCION Y PRESIONE EL BOTON");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("AUDITORIA");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("CONSULTA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(JbtnBuro7, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JbtnBuro1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                    .addComponent(JbtnBuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JbtnBuro2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JbtnBuro3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JbtnBuro12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JbtnBuro15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JbtnBuro4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JbtnBuro5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JbtnBuro6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JbtnBuro13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JbtnBuro16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JbtnBuro8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JbtnBuro9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JbtnBuro10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JbtnBuro11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JbtnBuro14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JbtnBuro17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(149, 149, 149))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbtnBuro1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbtnBuro4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbtnBuro8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbtnBuro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbtnBuro5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbtnBuro9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbtnBuro2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbtnBuro6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbtnBuro10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbtnBuro3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbtnBuro11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbtnBuro7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbtnBuro12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbtnBuro13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbtnBuro14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbtnBuro15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbtnBuro16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbtnBuro17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbtnBuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuroActionPerformed
        // Crear una instancia del JFrame de destino
        //        JFActualiza actualizaFrame = new JFActualiza();
        //        // Centrar el JFrame en la pantalla
        //
        //        actualizaFrame.pack();
        //        actualizaFrame.setLocationRelativeTo(null);
        //        // Hacer visible el JFrame de destino
        //        actualizaFrame.setVisible(true);

        // Opcional: Cerrar o esconder el JFrame actual si lo deseas
        this.dispose(); // Esto cierra la ventana actual
    }//GEN-LAST:event_JbtnBuroActionPerformed

    private void JbtnBuro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuro1ActionPerformed
        JTRegistroAlumnoVersion calificacion = new JTRegistroAlumnoVersion();
        // Centrar el JFrame en la pantalla
        calificacion.setLocationRelativeTo(null);
        // Hacer visible el JFrame de destino
        calificacion.setVisible(true);

        // Opcional: Cerrar o esconder la ventana actual
        this.dispose(); // Esto cierra la ventana actual, quítalo si no deseas cerrar esta ventana.
    }//GEN-LAST:event_JbtnBuro1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Cerrar la ventana actual (si es necesario)
        this.dispose(); // Esto cierra la ventana actual

        // Crear una nueva instancia del JFrame principal
        JFPrincipal principal = new JFPrincipal();
        principal.setLocationRelativeTo(null);
        // Hacer visible el JFrame principal
        principal.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JbtnBuro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbtnBuro2ActionPerformed

    private void JbtnBuro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuro3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbtnBuro3ActionPerformed

    private void JbtnBuro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuro4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbtnBuro4ActionPerformed

    private void JbtnBuro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuro5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbtnBuro5ActionPerformed

    private void JbtnBuro6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuro6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbtnBuro6ActionPerformed

    private void JbtnBuro7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuro7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbtnBuro7ActionPerformed

    private void JbtnBuro8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuro8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbtnBuro8ActionPerformed

    private void JbtnBuro9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuro9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbtnBuro9ActionPerformed

    private void JbtnBuro10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuro10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbtnBuro10ActionPerformed

    private void JbtnBuro11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuro11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbtnBuro11ActionPerformed

    private void JbtnBuro12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuro12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbtnBuro12ActionPerformed

    private void JbtnBuro13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuro13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbtnBuro13ActionPerformed

    private void JbtnBuro14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuro14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbtnBuro14ActionPerformed

    private void JbtnBuro15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuro15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbtnBuro15ActionPerformed

    private void JbtnBuro16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuro16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbtnBuro16ActionPerformed

    private void JbtnBuro17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuro17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbtnBuro17ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenuAdministrativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenuAdministrativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenuAdministrativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenuAdministrativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenuAdministrativos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnBuro;
    private javax.swing.JButton JbtnBuro1;
    private javax.swing.JButton JbtnBuro10;
    private javax.swing.JButton JbtnBuro11;
    private javax.swing.JButton JbtnBuro12;
    private javax.swing.JButton JbtnBuro13;
    private javax.swing.JButton JbtnBuro14;
    private javax.swing.JButton JbtnBuro15;
    private javax.swing.JButton JbtnBuro16;
    private javax.swing.JButton JbtnBuro17;
    private javax.swing.JButton JbtnBuro2;
    private javax.swing.JButton JbtnBuro3;
    private javax.swing.JButton JbtnBuro4;
    private javax.swing.JButton JbtnBuro5;
    private javax.swing.JButton JbtnBuro6;
    private javax.swing.JButton JbtnBuro7;
    private javax.swing.JButton JbtnBuro8;
    private javax.swing.JButton JbtnBuro9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
